development:
  recaptcha_public_key: <%= ENV['RECAPTCHA_PUBLIC_KEY'] %>
  recaptcha_private_key: <%= ENV['RECAPTCHA_PRIVATE_KEY'] %>
  secret_key_base: addb9afae9007bba522e3f40531a320dcd1f0fc3351b91d49736901e26e6e3fa86f70b9b8e5b4a58f3719da037cae9ed711690220b6bd3ae3bbfb098aabd0373

test:
  recaptcha_public_key: <%= ENV['RECAPTCHA_PUBLIC_KEY'] %>
  recaptcha_private_key: <%= ENV['RECAPTCHA_PRIVATE_KEY'] %>
  secret_key_base: e46557c421febb211953ac97a2d8bbfcc4733ebd40795c2d9bd62318842b8771bb052384d597a38b0d653d1f7fbdb3e0ba84239c5435de15103bbcee5ee3e79c

production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  from: <%= ENV['FROM'] %>
  host: <%= ENV['HOST'] %>
  recaptcha_public_key: <%= ENV['RECAPTCHA_PUBLIC_KEY'] %>
  recaptcha_private_key: <%= ENV['RECAPTCHA_PRIVATE_KEY'] %>
  smtp_port: <%= ENV['MAILGUN_SMTP_PORT'] %>
  smtp_address: <%= ENV['MAILGUN_SMTP_SERVER'] %>
  smtp_user_name: <%= ENV['MAILGUN_SMTP_LOGIN'] %>
  smtp_password: <%= ENV['MAILGUN_SMTP_PASSWORD'] %>
  smtp_domain: <%= ENV['MAILGUN_SMTP_DOMAIN'] %>
  mailgun_domain: <%= ENV['MAILGUN_DOMAIN'] %>
  mailgun_api_key: <%= ENV['MAILGUN_API_KEY'] %>
